export enum ReportType {
    SALES                = 'SALES',
    PRODUCT_PERFORMANCE  = 'PRODUCT_PERFORMANCE',
    INVENTORY_STATUS     = 'INVENTORY_STATUS',
    PROFIT_AND_LOSS      = 'PROFIT_AND_LOSS',
    CATEGORY_PERFORMANCE = 'CATEGORY_PERFORMANCE',
    DAILY_SUMMARY        = 'DAILY_SUMMARY',
}